### ISSUE TITLE
Problème utilisation librairie koheron avec "connect"

### ISSUE THREAD

**Issue by YoannGoular** [Koheron/koheron-sdk#343]
Bonjour l'équipe Koheron,

En ayant la dernière version d'OS proposée [(806de7a)](https://github.com/Koheron/koheron-sdk/releases/tag/v0.10.1) ainsi qu'avec le dernier environnement de Koheron-sdk, voilà le message d'erreur que j'obtiens après avoir généré le bitstream d'un instrument puis essayé d'utiliser de fichier de "test.py".

Commandes pour l'installation de l'environnement 

`$ git clone https://github.com/Koheron/koheron-sdk
$ cd koheron-sdk
$ sudo pip install -r requirements.txt`

Message d'erreur retourné

`devrp@devrp-VirtualBox:~/koheron-sdk/instruments/adc_dac$ python test.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from koheron import command, connect
ImportError: cannot import name connect
`

Auriez vous une idée de l'origine du problème ? 

Merci d'avance,
Yoann

**Comment by jeanminet** [comment]
Salut Yoann,

Merci pour ton retour. 
J'avais oublié de mettre à jour le fichier `requirements.txt` avec la dernière version du package python koheron.
Tu peux te mettre à jour en faisant simplement :
```
$ sudo pip install --upgrade koheron
```

Jean
