### ISSUE TITLE
Building project to an SD card image

### ISSUE THREAD

**Issue by grahamnaylorccfe** [Koheron/koheron-sdk#402]
Previously the method of building an SD card image from scratch was to first build the PL design in Vivado and then create the OS from the latest Ubuntu using the command:

make CONFIG=instruments/my_instrument linux
Has this command now been deprecated in the latest version?

**Comment by jeanminet** [comment]
The command is:
```
make CONFIG=example/led-blinker/config.yml os
```
This builds the FPGA, U-boot and the Linux kernel.
 You have then to run
```
sudo make CONFIG=example/led-blinker/config.yml image
```
This builds the SD card image with the Ubuntu root file system.

**Comment by grahamnaylorccfe** [comment]
Super - thanks.
Graham
