### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation in koheron.py

### ISSUE THREAD

**Issue by llombard** [Koheron/koheron-sdk#411]
```
  File "C:\Users\onera\Anaconda3\lib\site-packages\koheron\koheron.py", line 46
    else:
        ^
TabError: inconsistent use of tabs and spaces in indentation
```
solution: use automatic tab and space automator in pycharm on this file.

**Comment by jeanminet** [comment]
Thanks for spotting the error.
It seems to be a problem only with python3.
Fixed with 59f2b8fb

**Comment by llombard** [comment]
Not using python3 yet? ;-)

**Comment by jeanminet** [comment]
No...
Python2 is still the default version on Ubuntu 16.04
