### ISSUE TITLE
Fifo register allocation in c++ driver

### ISSUE THREAD

**Issue by CHV123** [Koheron/koheron-sdk#429]
Hi,

I've added a second AXI-4 Lite fifo to one of my instruments but I can't get any data out of it no matter how I arrange the ip in the block diagram. This leads me to think it's because I am using the same rdfd number for both fifo's in my c++ file. Would this be the case? If so, where can I find the relevant numbers for the second fifo?

Thanks for your help,
Charlie

**Comment by CHV123** [comment]
I've found sort of my answer in the documentation, and as I understand it these numbers should be the same for both. However, this still doesn't solve my problem so I was wondering if you might have any suggestions?

**Comment by jeanminet** [comment]
Hi Charlie,
As you said, the registers offsets should not change between the two FIFOs, only the base address is different.
Are you able to write and read the registers of the second FIFO ?
Jean

**Comment by CHV123** [comment]
I don't seem to be writing or reading to the second fifo. I diagnosed this by looking at the output of the relevant AXI clock converter and the data did not change when connected to the second fifo, but it does change when connected to the first.

**Comment by jeanminet** [comment]
Do you use the correct base address for the second FIFO ?
https://github.com/Koheron/koheron-sdk/blob/master/examples/pulse-generator/config.yml#L24
https://github.com/Koheron/koheron-sdk/blob/master/examples/pulse-generator/block_design.tcl#L105

**Comment by CHV123** [comment]
The base address in the config file and block design match. I would have also thought that if the memory addressing was incorrect then I would have got a similar behaviour to previously when the addressing was incorrect.

**Comment by jeanminet** [comment]
Then I don't know what to say.
You can send me your project by mail if you wish.

**Comment by CHV123** [comment]
I've solved the problem for the moment by using the one fifo and an AXI width converter
