### ISSUE TITLE
Running an instrument locally

### ISSUE THREAD

**Issue by CHV123** [Koheron/koheron-sdk#430]
Hi Jean,

I hope this hasn't already been asked but is it possible to run an instrument from the red pitaya itself, without going through the process of installing the koheron sdk on the board?

Thanks,
Charlie

**Comment by jeanminet** [comment]
Hi Charlie,

You can run an instrument (e.g. `led-blinker`) by running the following on the Red Pitaya:
```
$ bash /usr/local/api/app/install_instrument.sh <instrument_name>
```

**Comment by CHV123** [comment]
Thanks for this, I was having problems running my python test script but starting the instrument first seems to have sorted my problem.
