### ISSUE TITLE
examples/zedboard/led_blinker

### ISSUE THREAD

**Issue by grahamnaylorccfe** [Koheron/koheron-sdk#446]
test.py gives errors as it has a couple of small errors:
set_led in the class definition and the for loop should be 'set_leds' to correspond to the command in the led_blinker.hpp driver definition file in this directory (it sets all the LEDs, not the state of an individula LED). Similarly the get_forty_two command is absent from the .hpp file so gives an error when python tries to call it.

**Comment by jeanminet** [comment]
Thanks !

**Comment by grahamnaylorccfe** [comment]
And one more in test.py:
for i in range(255):


        driver.set_leds(i)


        time.sleep(0.01)
