### ISSUE TITLE
PDM optimization

### ISSUE THREAD

**Issue by pavel-demin** [Koheron/koheron-sdk#458]
Hello Koheron team,

I have a suggestion about your [PDM implementation](https://github.com/Koheron/koheron-sdk/blob/master/fpga/cores/pdm_v1_0/pdm.v).

I think that it can be replaced with the code from [this link](http://www.fpga4fun.com/PWM_DAC_2.html).

Best regards,

Pavel

**Comment by jeanminet** [comment]
Thank you Pavel.
This is much better!
Best regards,
Jean
