### ISSUE TITLE
make core

### ISSUE THREAD

**Issue by grahamnaylorccfe** [Koheron/koheron-sdk#461]
There seems to be an issue with the 'make CORE' command. Error reported when trying to make a core that had previously built correctly (before directories were re-structured):
![image](https://user-images.githubusercontent.com/11391609/37662429-f10422f6-2c4e-11e8-9b10-de34633afac8.png)

**Comment by jeanminet** [comment]
Thanks. Can you confirm you have the line: 
```
CONFIG ?= examples/red-pitaya/led-blinker/config.yml
```
at the beginning of your Makefile ?

**Comment by grahamnaylorccfe** [comment]
It was missing the redpitaya layer in the path. It works with the correct path now.
thanks
