### ISSUE TITLE
Dout Width in the slice block associated with FFT block

### ISSUE THREAD

**Issue by jinsanko** [Koheron/koheron-sdk#463]
I have a question on the set up for  “Dout Width” in the 4 slice blocks associated with FFT in the projects: spectrum, red-pitaya/FFT, alpha250/FFT. Are they supposed the same for all the 3 cases?
                          Dout Width before FFT /Dout Width after FFT
Spectrum  #1                  1                                          1
                  #0                 32                                         32
Red-pitaya/FFT #1           1                                          1
                          #0           1                                         32
Alpha259/FFT  #1             1                                          1
                         #0            1                                         32
Thank.

**Comment by jeanminet** [comment]
Hello,
Could you explain which slice blocks you are referring to ?
Thanks,
Jean

**Comment by jinsanko** [comment]
Sorry the mistake.
In spectrum
before FFT
slice_31_0_complex_mult_m_axis_dout_tdata    Dout Width=32
slice_63_32_complex_mult_m_axis_dout_tdata  Dout Width=1
after FFT
slice_31_0_fft_0_m_axis_data_tdata     Dout Width=32
slice_63_32_fft_0_m_axis_data_tdata   Dout Width=1

In red-pitaya/FFT/PSD
before FFT
slice_32_0_compex_mult_m_axis_dout_tdata   Dout Width=1
slice_72_40_compex_mult_m_axis_dout_tdata   Dout Width=1
after FFT
slice_31_0_fft_0_m_axis_data_tdata  Dout Width= 32
slice_63_32_fft_0_m_axis_data_tdata  Dout Width= 1

Are they supposed the same in both cases?

Thank.

**Comment by jeanminet** [comment]
I think the real Dout Width is the one that displays on `Dout[31:0]` (width = 31-0+1 = 32)

![image](https://user-images.githubusercontent.com/1735094/38494113-f79b22ee-3bf4-11e8-8f9b-c55e5ea5cf66.png)

As you noticed, Vivado displays a Dout Width of 1 when you click on the IP:

![image](https://user-images.githubusercontent.com/1735094/38494158-1e954032-3bf5-11e8-83e1-06aacf946bd1.png)

I think it is a bug of Vivado. 
This does not seem to have any effect.

**Comment by jinsanko** [comment]
Thank.
Please close this case.
