### ISSUE TITLE
 Warning: your client version 0.19.0 is incompatible with the server version 0.20.0.24d9686

### ISSUE THREAD

**Issue by grahamnaylorccfe** [Koheron/koheron-sdk#520]
Are there plans to upgrade the koheron python module so that it is compatible with the koheron version being built with the current version 0.20.0?
When I try and upgrade koheron with:
pip install --upgrade koheron
I get that the version installed is already the latest.

**Comment by tvanderbruggen** [comment]
Hi Graham,

I upgraded the koheron-python module.
Thanks for noticing.
