### ISSUE TITLE
ubuntu base image url unavailable 

### ISSUE THREAD

**Issue by okz** [Koheron/koheron-sdk#531]
I think the following URL is no longer available..

ubuntu_version=16.04.3
root_tar=ubuntu-base-${ubuntu_version}-base-armhf.tar.gz
root_url=http://cdimage.ubuntu.com/ubuntu-base/releases/${ubuntu_version}/release/$root_tar

The download attempt quietely downloads this, as a ``.tar.gz`` is generated but with a 404 error: 

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at cdimage.ubuntu.com Port 80</address>
</body></html>
```

And then all you get while trying to build the image is: 

```
gzip: stdin: not in gzip format
```

Maybe the curl's -f  could be used to highlight the problem with the downloads ? 
https://superuser.com/questions/590099/can-i-make-curl-fail-with-an-exitcode-different-than-0-if-the-http-status-code-i

**Comment by jeanminet** [comment]
Thanks a lot for reporting the issue.
We need to upgrade to the version 16.04.6 of Ubuntu which is the only one left on the Ubuntu server: #532
