### ISSUE TITLE
Unable to locate package g++-9-arm-linux-gnueabihf

### ISSUE THREAD

**Issue by koraykzly** [Koheron/koheron-sdk#541]
Hello,

I try to use Vivado HLx 2017.2 on Ubuntu 16.04.1 version on virtual box.
I followed these instructions exactly: https://www.koheron.com/software-development-kit/documentation/setup-development-machine/

But, when I run `make setup` command these errors occur:

![ss](https://user-images.githubusercontent.com/45359175/127740554-9700cd31-854e-480e-886a-d10e17f518f0.png)

Thanks.

**Comment by jeanminet** [comment]
We recently upgraded the SDK for Ubuntu 20.04.

You need to follow this instructions to install GCC9 on Ubuntu 16.04:
https://gist.github.com/alexandreelise/192a63e287018ddfc896bbcb70b219d4
