### ISSUE TITLE
FFT example

### ISSUE THREAD

**Issue by v-shetty** [Koheron/koheron-sdk#552]
Hi Team,

In the FFT example, where is the computation happening in FFT calculation?

if i see the design, i dont see any FFT block in vivado design

**Comment by tvanderbruggen** [comment]
The FFT is implemented in the power spectral density module:

https://github.com/Koheron/koheron-sdk/blob/master/examples/alpha250/fft/tcl/power_spectral_density.tcl

**Comment by v-shetty** [comment]
thank you for your intime response.
Iam closing the issue
